function Events = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  EVENTS = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  EVENTS = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  Events = importfile("/Users/solgaleo/Documents/Columbia Courseworks/Activities/Coursera/Exploratory Data Analysis with MATLAB/StormEvents/StormEvents_2013.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 18-Apr-2020 00:08:40

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 23);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "Month", "Event_Type", "Begin", "Var8", "End", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Episode_Narrative", "Var23"];
opts.SelectedVariableNames = ["Month", "Event_Type", "Begin", "End", "Episode_Narrative"];
opts.VariableTypes = ["string", "string", "string", "string", "categorical", "categorical", "datetime", "string", "datetime", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var8", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Episode_Narrative", "Var23"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Month", "Event_Type", "Var8", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Episode_Narrative", "Var23"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Begin", "InputFormat", "yyyy-MM-dd HH:mm:ss");
opts = setvaropts(opts, "End", "InputFormat", "yyyy-MM-dd HH:mm:ss");

% Import the data
Events = readtable(filename, opts);

end