function stormData = importfile1(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  STORMDATA = IMPORTFILE1(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  STORMDATA = IMPORTFILE1(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  stormData = importfile1("/Users/solgaleo/Documents/Columbia Courseworks/Activities/Coursera/Exploratory Data Analysis with MATLAB/StormEvents/StormEvents_2017_finalProject.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 18-Apr-2020 22:01:16

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 24);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "State", "Var4", "Month", "Event_Type", "CZ_Name", "Begin_Date_Time", "Var9", "End_Date_Time", "Injuries_Direct", "Var12", "Deaths_Direct", "Var14", "Var15", "Property_Cost", "Var17", "Crop_Cost", "Begin_Lat", "Begin_Lon", "End_Lat", "End_Lon", "Episode_Narrative", "Event_Narrative"];
opts.SelectedVariableNames = ["State", "Month", "Event_Type", "CZ_Name", "Begin_Date_Time", "End_Date_Time", "Injuries_Direct", "Deaths_Direct", "Property_Cost", "Crop_Cost", "Begin_Lat", "Begin_Lon", "End_Lat", "End_Lon", "Episode_Narrative", "Event_Narrative"];
opts.VariableTypes = ["string", "string", "categorical", "string", "categorical", "categorical", "categorical", "datetime", "string", "datetime", "double", "string", "double", "string", "string", "double", "string", "double", "double", "double", "double", "double", "categorical", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var4", "Var9", "Var12", "Var14", "Var15", "Var17", "Event_Narrative"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "State", "Var4", "Month", "Event_Type", "CZ_Name", "Var9", "Var12", "Var14", "Var15", "Var17", "Episode_Narrative", "Event_Narrative"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Begin_Date_Time", "InputFormat", "yyyy-MM-dd HH:mm:ss");
opts = setvaropts(opts, "End_Date_Time", "InputFormat", "yyyy-MM-dd HH:mm:ss");

% Import the data
stormData = readtable(filename, opts);

end